export const categories = [
  { id: "all", name: "All Products" },
  { id: "gaming-pc", name: "Gaming PCs" },
  { id: "laptop", name: "Laptops" },
  { id: "peripheral", name: "Peripherals" },
  { id: "storage", name: "Storage" },
  { id: "components", name: "Components" },
]

export const products = [
  {
    id: 1,
    name: "RTX 4090 Gaming Beast",
    category: "gaming-pc",
    price: 249000,
    originalPrice: 260000,
    image: "/images/hero-gaming-pc.jpg",
    rating: 4.9,
    reviews: 124,
    badge: "Best Seller",
    description: "Ultimate gaming PC with RTX 4090, Intel i9, 64GB RAM",
    specs: ["Intel i9-13900K", "64GB DDR5", "RTX 4090 24GB", "2TB NVMe SSD"],
  },
  {
    id: 2,
    name: "Elite Gaming Rig",
    category: "gaming-pc",
    price: 230000,
    originalPrice: 2199,
    image: "/images/Elite Gaming Rig.jpg",
    rating: 4.7,
    reviews: 78,
    badge: "New",
    description: "Mid-range gaming PC with RTX 4070, Ryzen 7",
    specs: ["Intel i7-13700K", "32GB DDR5", "RTX 4080 16GB", "1TB NVMe SSD"],
  },
	{
    id: 3,
    name: "Elite Gaming Rig",
    category: "gaming-pc",
    price: 200000,
    originalPrice: 2199,
    image: "/images/Elite Gaming.jpg",
    rating: 4.7,
    reviews: 78,
    badge: "New",
    description: "Mid-range gaming PC with RTX 4070, Ryzen 7",
    specs: ["Intel i7-13700K", "32GB DDR5", "RTX 4080 16GB", "1TB NVMe SSD"],
  },
  {
    id: 4,
    name: "ProBook 450 G10",
    category: "laptop",
    price: 275000,
    originalPrice: 1099,
    image: "/images/laptop-probook.jpg",
    rating: 4.7,
    reviews: 89,
    badge: "Business",
    description: "Professional laptop for business productivity",
    specs: ["Intel i5-1335U", "16GB RAM", "512GB SSD", "15.6\" FHD"],
  },
  {
    id: 5,
    name: "Envy x360 15",
    category: "laptop",
    price: 150000,
    originalPrice: 1499,
    image: "/images/envy-laptop.jpg",
    rating: 4.8,
    reviews: 156,
    badge: "Premium",
    description: "Elegant 2-in-1 convertible with stunning display",
    specs: ["AMD Ryzen 7", "16GB RAM", "1TB SSD", "15.6\" OLED Touch"],
  },
  {
    id: 6,
    name: "Apex Pro TKL Keyboard",
    category: "peripheral",
    price: 5500,
    originalPrice: 229,
    image: "/images/mechanical-keyboard.jpg",
    rating: 4.9,
    reviews: 312,
    badge: "Popular",
    description: "Mechanical keyboard with adjustable actuation",
    specs: ["Cherry MX Red", "RGB Backlit", "Aluminum Frame", "USB-C"],
  },
  {
    id: 7,
    name: "DeathAdder V3 Pro Mouse",
    category: "peripheral",
    price: 2500,
    originalPrice: 179,
    image: "/images/gaming-mouse.jpg",
    rating: 4.8,
    reviews: 267,
    badge: "Gaming",
    description: "Ultra-lightweight wireless gaming mouse",
    specs: ["25600 DPI", "Wireless", "70hr Battery", "RGB Lighting"],
  },
  {
    id: 8,
    name: "Samsung 990 Pro 2TB",
    category: "storage",
    price: 1800,
    originalPrice: 249,
    image: "/images/ssd-storage.jpg",
    rating: 4.9,
    reviews: 445,
    badge: "Hot Deal",
    description: "NVMe SSD with 7450MB/s read speeds",
    specs: ["7450MB/s Read", "NVMe Gen4", "2TB Capacity", "5-Year Warranty"],
  },
  {
    id: 9,
    name: "WD Black 4TB HDD",
    category: "storage",
    price: 12000,
    originalPrice: 149,
    image: "/images/hdd-storage.jpg",
    rating: 4.6,
    reviews: 198,
    badge: "Value",
    description: "High-capacity external storage solution",
    specs: ["7200 RPM", "256MB Cache", "4TB Capacity", "5-Year Warranty"],
  },
  {
    id: 10,
    name: "Intel Core i9-14900K",
    category: "components",
    price: 280000,
    originalPrice: 649,
    image: "/images/ssd-storage.jpg",
    rating: 4.8,
    reviews: 145,
    badge: "New",
    description: "Flagship desktop processor for enthusiasts",
    specs: ["24 Cores", "6.0GHz Boost", "36MB Cache", "LGA 1700"],
  },
  {
    id: 11,
    name: "RTX 4070 Ti Super",
    category: "components",
    price: 180000,
    originalPrice: 899,
    image: "/images/tie super.jpg",
    rating: 4.9,
    reviews: 203,
    badge: "Gaming",
    description: "High-performance graphics card for 4K gaming",
    specs: ["16GB GDDR6X", "2610MHz Boost", "Ray Tracing", "DLSS 3"],
  },
  {
    id: 12,
    name: "Scanner",
    category: "components",
    price: 125000,
    originalPrice: 10000,
    image: "/images/scanner.jpg",
    rating: 4.9,
    reviews: 203,
    badge: "new",
    description: "High-performance scanner",
	specs: ["High-performance scanner"],
  },
]
